// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db_gen

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        string
	Name      string
	Bio       string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Book struct {
	ID        string
	Title     string
	Isbn      string
	Year      int32
	Pages     int32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type BooksAuthor struct {
	BookID   string
	AuthorID string
}

type BooksSubject struct {
	BookID    string
	SubjectID string
}

type Quote struct {
	ID        string
	Content   string
	Page      int32
	BookID    string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Subject struct {
	ID          string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}
