// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: subject.sql

package db_gen

import (
	"context"
	"time"
)

const createSubject = `-- name: CreateSubject :exec
INSERT INTO subjects (id, name, description, created_at) VALUES ($1, $2, $3, $4)
`

type CreateSubjectParams struct {
	ID          string
	Name        string
	Description string
	CreatedAt   time.Time
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, createSubject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}
